
// This file has been generated by the GUI designer. Do not modify.
namespace GuiWidgets
{
	public partial class TitleBox
	{
		private global::Gtk.EventBox eventboxTitleBar;
		private global::Gtk.VBox vboxTitleBar;
		private global::Gtk.HBox hboxTitleBarTop;
		private global::Gtk.EventBox eventboxCaption;
		private global::Gtk.Label labelCaption;
		private global::Gtk.EventBox eventboxButtons;
		private global::Gtk.HBox hboxButtons;
		private global::Gtk.Button buttonMinimize;
		private global::Gtk.Button buttonMaximize;
		private global::Gtk.Button buttonClose;
		private global::Gtk.EventBox eventboxTitleBarBottom;
		private global::Gtk.HSeparator hseparatorTitleBarBottom;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GuiWidgets.TitleBox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GuiWidgets.TitleBox";
			// Container child GuiWidgets.TitleBox.Gtk.Container+ContainerChild
			this.eventboxTitleBar = new global::Gtk.EventBox ();
			this.eventboxTitleBar.Name = "eventboxTitleBar";
			// Container child eventboxTitleBar.Gtk.Container+ContainerChild
			this.vboxTitleBar = new global::Gtk.VBox ();
			this.vboxTitleBar.Name = "vboxTitleBar";
			// Container child vboxTitleBar.Gtk.Box+BoxChild
			this.hboxTitleBarTop = new global::Gtk.HBox ();
			this.hboxTitleBarTop.Name = "hboxTitleBarTop";
			// Container child hboxTitleBarTop.Gtk.Box+BoxChild
			this.eventboxCaption = new global::Gtk.EventBox ();
			this.eventboxCaption.Name = "eventboxCaption";
			// Container child eventboxCaption.Gtk.Container+ContainerChild
			this.labelCaption = new global::Gtk.Label ();
			this.labelCaption.Name = "labelCaption";
			this.labelCaption.Xpad = 7;
			this.labelCaption.Xalign = 0F;
			this.labelCaption.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
			this.labelCaption.SingleLineMode = true;
			this.eventboxCaption.Add (this.labelCaption);
			this.hboxTitleBarTop.Add (this.eventboxCaption);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxTitleBarTop [this.eventboxCaption]));
			w2.Position = 0;
			// Container child hboxTitleBarTop.Gtk.Box+BoxChild
			this.eventboxButtons = new global::Gtk.EventBox ();
			this.eventboxButtons.Name = "eventboxButtons";
			// Container child eventboxButtons.Gtk.Container+ContainerChild
			this.hboxButtons = new global::Gtk.HBox ();
			this.hboxButtons.Name = "hboxButtons";
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.buttonMinimize = new global::Gtk.Button ();
			this.buttonMinimize.WidthRequest = 22;
			this.buttonMinimize.HeightRequest = 22;
			this.buttonMinimize.CanFocus = true;
			this.buttonMinimize.Name = "buttonMinimize";
			this.buttonMinimize.UseUnderline = true;
			this.buttonMinimize.Xalign = 0F;
			// Container child buttonMinimize.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-bottom", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w4.Add (w7);
			w3.Add (w4);
			this.buttonMinimize.Add (w3);
			this.hboxButtons.Add (this.buttonMinimize);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.buttonMinimize]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.buttonMaximize = new global::Gtk.Button ();
			this.buttonMaximize.WidthRequest = 22;
			this.buttonMaximize.HeightRequest = 22;
			this.buttonMaximize.CanFocus = true;
			this.buttonMaximize.Name = "buttonMaximize";
			this.buttonMaximize.UseUnderline = true;
			// Container child buttonMaximize.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-top", global::Gtk.IconSize.Menu);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w13.Add (w16);
			w12.Add (w13);
			this.buttonMaximize.Add (w12);
			this.hboxButtons.Add (this.buttonMaximize);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.buttonMaximize]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.WidthRequest = 22;
			this.buttonClose.HeightRequest = 22;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			// Container child buttonClose.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w22.Add (w25);
			w21.Add (w22);
			this.buttonClose.Add (w21);
			this.hboxButtons.Add (this.buttonClose);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.buttonClose]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.eventboxButtons.Add (this.hboxButtons);
			this.hboxTitleBarTop.Add (this.eventboxButtons);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hboxTitleBarTop [this.eventboxButtons]));
			w31.PackType = ((global::Gtk.PackType)(1));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.vboxTitleBar.Add (this.hboxTitleBarTop);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vboxTitleBar [this.hboxTitleBarTop]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vboxTitleBar.Gtk.Box+BoxChild
			this.eventboxTitleBarBottom = new global::Gtk.EventBox ();
			this.eventboxTitleBarBottom.Name = "eventboxTitleBarBottom";
			// Container child eventboxTitleBarBottom.Gtk.Container+ContainerChild
			this.hseparatorTitleBarBottom = new global::Gtk.HSeparator ();
			this.hseparatorTitleBarBottom.Name = "hseparatorTitleBarBottom";
			this.eventboxTitleBarBottom.Add (this.hseparatorTitleBarBottom);
			this.vboxTitleBar.Add (this.eventboxTitleBarBottom);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vboxTitleBar [this.eventboxTitleBarBottom]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.eventboxTitleBar.Add (this.vboxTitleBar);
			this.Add (this.eventboxTitleBar);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
