
// This file has been generated by the GUI designer. Do not modify.
namespace ColorPicker
{
	public partial class test
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ColorPicker.test
			this.Name = "ColorPicker.test";
			this.Title = global::Mono.Unix.Catalog.GetString ("test");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
