
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::ColorPicker.ColorSpectrum colorSpectrum;
	private global::ColorPicker.ColorSquare colorSquare;
	private global::Gtk.HScale redScale;
	private global::Gtk.HScale greenScale;
	private global::Gtk.HScale blueScale;
	private global::Gtk.HScale alphaScale;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.DrawingArea colorView;
	private global::Gtk.Label label5;
	private global::Gtk.Entry colorCode;
	private global::ColorPicker.ColorSaturation colorSaturation;
	private global::ColorPicker.ColorBrightness colorBrightness;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.colorSpectrum = new global::ColorPicker.ColorSpectrum ();
		this.colorSpectrum.WidthRequest = 256;
		this.colorSpectrum.HeightRequest = 128;
		this.colorSpectrum.Name = "colorSpectrum";
		this.colorSpectrum.Red = ((ushort)(0));
		this.colorSpectrum.Green = ((ushort)(0));
		this.colorSpectrum.Blue = ((ushort)(0));
		this.fixed1.Add (this.colorSpectrum);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.colorSpectrum]));
		w1.X = 255;
		w1.Y = 9;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.colorSquare = new global::ColorPicker.ColorSquare ();
		this.colorSquare.WidthRequest = 128;
		this.colorSquare.HeightRequest = 128;
		this.colorSquare.Name = "colorSquare";
		this.fixed1.Add (this.colorSquare);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.colorSquare]));
		w2.X = 72;
		w2.Y = 9;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.redScale = new global::Gtk.HScale (null);
		this.redScale.WidthRequest = 128;
		this.redScale.CanFocus = true;
		this.redScale.Name = "redScale";
		this.redScale.Adjustment.Upper = 255D;
		this.redScale.Adjustment.PageIncrement = 10D;
		this.redScale.Adjustment.StepIncrement = 1D;
		this.redScale.Adjustment.Value = 255D;
		this.redScale.DrawValue = true;
		this.redScale.Digits = 0;
		this.redScale.ValuePos = ((global::Gtk.PositionType)(2));
		this.fixed1.Add (this.redScale);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.redScale]));
		w3.X = 85;
		w3.Y = 164;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.greenScale = new global::Gtk.HScale (null);
		this.greenScale.WidthRequest = 128;
		this.greenScale.CanFocus = true;
		this.greenScale.Name = "greenScale";
		this.greenScale.Adjustment.Upper = 255D;
		this.greenScale.Adjustment.PageIncrement = 10D;
		this.greenScale.Adjustment.StepIncrement = 1D;
		this.greenScale.Adjustment.Value = 255D;
		this.greenScale.DrawValue = true;
		this.greenScale.Digits = 0;
		this.greenScale.ValuePos = ((global::Gtk.PositionType)(2));
		this.fixed1.Add (this.greenScale);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.greenScale]));
		w4.X = 85;
		w4.Y = 213;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.blueScale = new global::Gtk.HScale (null);
		this.blueScale.WidthRequest = 128;
		this.blueScale.CanFocus = true;
		this.blueScale.Name = "blueScale";
		this.blueScale.Adjustment.Upper = 255D;
		this.blueScale.Adjustment.PageIncrement = 10D;
		this.blueScale.Adjustment.StepIncrement = 1D;
		this.blueScale.Adjustment.Value = 255D;
		this.blueScale.DrawValue = true;
		this.blueScale.Digits = 0;
		this.blueScale.ValuePos = ((global::Gtk.PositionType)(2));
		this.fixed1.Add (this.blueScale);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.blueScale]));
		w5.X = 85;
		w5.Y = 262;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.alphaScale = new global::Gtk.HScale (null);
		this.alphaScale.WidthRequest = 128;
		this.alphaScale.CanFocus = true;
		this.alphaScale.Name = "alphaScale";
		this.alphaScale.Adjustment.Upper = 255D;
		this.alphaScale.Adjustment.PageIncrement = 10D;
		this.alphaScale.Adjustment.StepIncrement = 1D;
		this.alphaScale.Adjustment.Value = 255D;
		this.alphaScale.DrawValue = true;
		this.alphaScale.Digits = 0;
		this.alphaScale.ValuePos = ((global::Gtk.PositionType)(2));
		this.fixed1.Add (this.alphaScale);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.alphaScale]));
		w6.X = 85;
		w6.Y = 311;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Red");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w7.X = 36;
		w7.Y = 181;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Green");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w8.X = 30;
		w8.Y = 229;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Blue");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w9.X = 32;
		w9.Y = 280;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Alpha");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w10.X = 27;
		w10.Y = 328;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.colorView = new global::Gtk.DrawingArea ();
		this.colorView.WidthRequest = 60;
		this.colorView.HeightRequest = 60;
		this.colorView.Name = "colorView";
		this.fixed1.Add (this.colorView);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.colorView]));
		w11.X = 284;
		w11.Y = 288;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Color");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w12.X = 391;
		w12.Y = 305;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.colorCode = new global::Gtk.Entry ();
		this.colorCode.WidthRequest = 70;
		this.colorCode.CanFocus = true;
		this.colorCode.Name = "colorCode";
		this.colorCode.Text = global::Mono.Unix.Catalog.GetString ("#FFFFFF");
		this.colorCode.IsEditable = true;
		this.colorCode.InvisibleChar = '●';
		this.fixed1.Add (this.colorCode);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.colorCode]));
		w13.X = 373;
		w13.Y = 330;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.colorSaturation = new global::ColorPicker.ColorSaturation ();
		this.colorSaturation.WidthRequest = 128;
		this.colorSaturation.HeightRequest = 14;
		this.colorSaturation.Name = "colorSaturation";
		this.fixed1.Add (this.colorSaturation);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.colorSaturation]));
		w14.X = 72;
		w14.Y = 146;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.colorBrightness = new global::ColorPicker.ColorBrightness ();
		this.colorBrightness.WidthRequest = 14;
		this.colorBrightness.HeightRequest = 128;
		this.colorBrightness.Name = "colorBrightness";
		this.fixed1.Add (this.colorBrightness);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.colorBrightness]));
		w15.X = 215;
		w15.Y = 9;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 536;
		this.DefaultHeight = 411;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.redScale.ValueChanged += new global::System.EventHandler (this.OnRedScaleValueChanged);
		this.greenScale.ValueChanged += new global::System.EventHandler (this.OnGreenScaleValueChanged);
		this.blueScale.ValueChanged += new global::System.EventHandler (this.OnBlueScaleValueChanged);
		this.colorCode.Changed += new global::System.EventHandler (this.OnColorCodeChanged);
	}
}
