
// This file has been generated by the GUI designer. Do not modify.
namespace Gui
{
	public partial class CustomFileChooserDialog
	{
		private global::Gtk.VBox vboxFileChooser;
		private global::Gtk.FileChooserWidget fileChooser;
		private global::Gtk.HBox hboxButtons;
		private global::Gtk.Button btnCancel;
		private global::Gtk.Button btnOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gui.CustomFileChooserDialog
			this.Name = "Gui.CustomFileChooserDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("CustomFileChooserDialog");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Decorated = false;
			// Container child Gui.CustomFileChooserDialog.Gtk.Container+ContainerChild
			this.vboxFileChooser = new global::Gtk.VBox ();
			this.vboxFileChooser.Name = "vboxFileChooser";
			this.vboxFileChooser.Spacing = 6;
			this.vboxFileChooser.BorderWidth = ((uint)(6));
			// Container child vboxFileChooser.Gtk.Box+BoxChild
			this.fileChooser = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(0)));
			this.fileChooser.Name = "fileChooser";
			this.vboxFileChooser.Add (this.fileChooser);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxFileChooser [this.fileChooser]));
			w1.Position = 0;
			// Container child vboxFileChooser.Gtk.Box+BoxChild
			this.hboxButtons = new global::Gtk.HBox ();
			this.hboxButtons.Name = "hboxButtons";
			this.hboxButtons.Spacing = 6;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.WidthRequest = 100;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hboxButtons.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.btnCancel]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnOk = new global::Gtk.Button ();
			this.btnOk.WidthRequest = 100;
			this.btnOk.CanFocus = true;
			this.btnOk.Name = "btnOk";
			this.btnOk.UseUnderline = true;
			this.btnOk.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			this.hboxButtons.Add (this.btnOk);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.btnOk]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vboxFileChooser.Add (this.hboxButtons);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxFileChooser [this.hboxButtons]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vboxFileChooser);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 500;
			this.DefaultHeight = 400;
			this.Hide ();
		}
	}
}
