
// This file has been generated by the GUI designer. Do not modify.
namespace Gui
{
	public partial class CustomFileChooserDialog
	{
		private global::Gtk.Table table1;
		private global::Gtk.FileChooserWidget fileChooser;
		private global::Gtk.HBox hboxButtons;
		private global::Gtk.Button btnCancel;
		private global::Gtk.Button btnOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gui.CustomFileChooserDialog
			this.Name = "Gui.CustomFileChooserDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("CustomFileChooserDialog");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.DefaultWidth = 640;
			this.DefaultHeight = 480;
			this.Decorated = false;
			// Container child Gui.CustomFileChooserDialog.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.fileChooser = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(1)));
			this.fileChooser.Name = "fileChooser";
			this.table1.Add (this.fileChooser);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.fileChooser]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hboxButtons = new global::Gtk.HBox ();
			this.hboxButtons.Name = "hboxButtons";
			this.hboxButtons.Spacing = 6;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.WidthRequest = 100;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hboxButtons.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.btnCancel]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnOk = new global::Gtk.Button ();
			this.btnOk.WidthRequest = 100;
			this.btnOk.CanFocus = true;
			this.btnOk.Name = "btnOk";
			this.btnOk.UseUnderline = true;
			this.btnOk.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			this.hboxButtons.Add (this.btnOk);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxButtons [this.btnOk]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.table1.Add (this.hboxButtons);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.hboxButtons]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
