
// This file has been generated by the GUI designer. Do not modify.
namespace Gui
{
	public partial class CustomMessageDialog
	{
		private global::Gtk.VBox vboxMsgDlg;
		private global::Gtk.HBox hboxDetail;
		private global::Gtk.Image imageType;
		private global::Gtk.Label lText;
		private global::Gtk.HButtonBox hbtnboxAction;
		private global::Gtk.Button btn1;
		private global::Gtk.Button btn2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gui.CustomMessageDialog
			this.Name = "Gui.CustomMessageDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("CustomMessageDialog");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.Decorated = false;
			// Container child Gui.CustomMessageDialog.Gtk.Container+ContainerChild
			this.vboxMsgDlg = new global::Gtk.VBox ();
			this.vboxMsgDlg.Name = "vboxMsgDlg";
			this.vboxMsgDlg.Spacing = 6;
			this.vboxMsgDlg.BorderWidth = ((uint)(6));
			// Container child vboxMsgDlg.Gtk.Box+BoxChild
			this.hboxDetail = new global::Gtk.HBox ();
			this.hboxDetail.Name = "hboxDetail";
			this.hboxDetail.Spacing = 6;
			// Container child hboxDetail.Gtk.Box+BoxChild
			this.imageType = new global::Gtk.Image ();
			this.imageType.Name = "imageType";
			this.imageType.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-error", global::Gtk.IconSize.Dialog);
			this.hboxDetail.Add (this.imageType);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxDetail [this.imageType]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hboxDetail.Gtk.Box+BoxChild
			this.lText = new global::Gtk.Label ();
			this.lText.Name = "lText";
			this.lText.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hboxDetail.Add (this.lText);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxDetail [this.lText]));
			w2.Position = 1;
			this.vboxMsgDlg.Add (this.hboxDetail);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMsgDlg [this.hboxDetail]));
			w3.Position = 0;
			// Container child vboxMsgDlg.Gtk.Box+BoxChild
			this.hbtnboxAction = new global::Gtk.HButtonBox ();
			this.hbtnboxAction.Name = "hbtnboxAction";
			// Container child hbtnboxAction.Gtk.ButtonBox+ButtonBoxChild
			this.btn1 = new global::Gtk.Button ();
			this.btn1.CanFocus = true;
			this.btn1.Name = "btn1";
			this.btn1.UseUnderline = true;
			this.btn1.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			this.hbtnboxAction.Add (this.btn1);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnboxAction [this.btn1]));
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbtnboxAction.Gtk.ButtonBox+ButtonBoxChild
			this.btn2 = new global::Gtk.Button ();
			this.btn2.CanFocus = true;
			this.btn2.Name = "btn2";
			this.btn2.UseUnderline = true;
			this.btn2.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbtnboxAction.Add (this.btn2);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbtnboxAction [this.btn2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vboxMsgDlg.Add (this.hbtnboxAction);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxMsgDlg [this.hbtnboxAction]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vboxMsgDlg);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 300;
			this.DefaultHeight = 200;
			this.Hide ();
		}
	}
}
