
// This file has been generated by the GUI designer. Do not modify.
namespace FontTool
{
	public partial class FontStyleWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action SaveAction;
		private global::Gtk.Action CloseAction;
		private global::Gtk.Action SettingsAction;
		private global::Gtk.Action FontAction;
		private global::Gtk.Action WindowStyleAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action AboutAction;
		private global::Gtk.RadioAction CustomStyleAction;
		private global::Gtk.RadioAction PlatformStyleAction;
		private global::Gtk.RadioAction DecoratedCustomStyleAction;
		private global::Gtk.ToggleAction OnlyEnglishAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeFont;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label lPreview;
		private global::Gtk.DrawingArea preview;
		private global::Gtk.Entry ePreviewSample;
		private global::Gtk.Table table1;
		private global::Gtk.CheckButton cbBold;
		private global::Gtk.CheckButton cbItalic;
		private global::Gtk.CheckButton cbStrikeout;
		private global::Gtk.CheckButton cbUnderline;
		private global::Gtk.Label lSize;
		private global::Gtk.Label lStretch;
		private global::Gtk.SpinButton sbSize;
		private global::Gtk.SpinButton sbStretch;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FontTool.FontStyleWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action (
				"FileAction",
				global::Mono.Unix.Catalog.GetString("File"),
				null,
				null
			);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.SaveAction = new global::Gtk.Action (
				"SaveAction",
				global::Mono.Unix.Catalog.GetString("Save"),
				null,
				null
			);
			this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
			w1.Add (this.SaveAction, null);
			this.CloseAction = new global::Gtk.Action (
				"CloseAction",
				global::Mono.Unix.Catalog.GetString("Close"),
				null,
				null
			);
			this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
			w1.Add (this.CloseAction, null);
			this.SettingsAction = new global::Gtk.Action (
				"SettingsAction",
				global::Mono.Unix.Catalog.GetString("Settings"),
				null,
				null
			);
			this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
			w1.Add (this.SettingsAction, null);
			this.FontAction = new global::Gtk.Action (
				"FontAction",
				global::Mono.Unix.Catalog.GetString("Font"),
				null,
				null
			);
			this.FontAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Font");
			w1.Add (this.FontAction, null);
			this.WindowStyleAction = new global::Gtk.Action (
				"WindowStyleAction",
				global::Mono.Unix.Catalog.GetString("Window style"),
				null,
				null
			);
			this.WindowStyleAction.Sensitive = false;
			this.WindowStyleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Window style");
			this.WindowStyleAction.Visible = false;
			w1.Add (this.WindowStyleAction, null);
			this.HelpAction = new global::Gtk.Action (
				"HelpAction",
				global::Mono.Unix.Catalog.GetString("Help"),
				null,
				null
			);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.AboutAction = new global::Gtk.Action (
				"AboutAction",
				global::Mono.Unix.Catalog.GetString("About"),
				null,
				null
			);
			this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.AboutAction, null);
			this.CustomStyleAction = new global::Gtk.RadioAction (
				"CustomStyleAction",
				global::Mono.Unix.Catalog.GetString("DGLE2"),
				null,
				null,
				0
			);
			this.CustomStyleAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.CustomStyleAction.Sensitive = false;
			this.CustomStyleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("DGLE2");
			this.CustomStyleAction.Visible = false;
			w1.Add (this.CustomStyleAction, null);
			this.PlatformStyleAction = new global::Gtk.RadioAction (
				"PlatformStyleAction",
				global::Mono.Unix.Catalog.GetString("Platform"),
				null,
				null,
				0
			);
			this.PlatformStyleAction.Group = this.CustomStyleAction.Group;
			this.PlatformStyleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Platform");
			w1.Add (this.PlatformStyleAction, null);
			this.DecoratedCustomStyleAction = new global::Gtk.RadioAction (
				"DecoratedCustomStyleAction",
				global::Mono.Unix.Catalog.GetString("Decorated DGLE2"),
				null,
				null,
				0
			);
			this.DecoratedCustomStyleAction.Group = this.CustomStyleAction.Group;
			this.DecoratedCustomStyleAction.Sensitive = false;
			this.DecoratedCustomStyleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Decorated DGLE2");
			this.DecoratedCustomStyleAction.Visible = false;
			w1.Add (this.DecoratedCustomStyleAction, null);
			this.OnlyEnglishAction = new global::Gtk.ToggleAction (
				"OnlyEnglishAction",
				global::Mono.Unix.Catalog.GetString("Only English"),
				null,
				null
			);
			this.OnlyEnglishAction.Active = true;
			this.OnlyEnglishAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Only English");
			w1.Add (this.OnlyEnglishAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 500;
			this.HeightRequest = 500;
			this.CanDefault = true;
			this.Name = "FontTool.FontStyleWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("FontStyleWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child FontTool.FontStyleWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='SaveAction' action='SaveAction'/><menuitem name='CloseAction' action='CloseAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menu name='FontAction' action='FontAction'><menuitem name='OnlyEnglishAction' action='OnlyEnglishAction'/></menu></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeFont = new global::Gtk.TreeView ();
			this.treeFont.CanFocus = true;
			this.treeFont.Name = "treeFont";
			this.GtkScrolledWindow.Add (this.treeFont);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w4.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lPreview = new global::Gtk.Label ();
			this.lPreview.Name = "lPreview";
			this.lPreview.Xalign = 0F;
			this.lPreview.LabelProp = global::Mono.Unix.Catalog.GetString ("Preview");
			this.vbox6.Add (this.lPreview);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lPreview]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.preview = new global::Gtk.DrawingArea ();
			this.preview.HeightRequest = 90;
			this.preview.Name = "preview";
			this.vbox6.Add (this.preview);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.preview]));
			w6.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.ePreviewSample = new global::Gtk.Entry ();
			this.ePreviewSample.CanFocus = true;
			this.ePreviewSample.Name = "ePreviewSample";
			this.ePreviewSample.Text = global::Mono.Unix.Catalog.GetString ("DGLE2 is here!");
			this.ePreviewSample.IsEditable = true;
			this.ePreviewSample.InvisibleChar = '●';
			this.vbox6.Add (this.ePreviewSample);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.ePreviewSample]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add (this.vbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox6]));
			w8.Position = 1;
			w8.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(4)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(12));
			this.table1.ColumnSpacing = ((uint)(12));
			// Container child table1.Gtk.Table+TableChild
			this.cbBold = new global::Gtk.CheckButton ();
			this.cbBold.CanFocus = true;
			this.cbBold.Name = "cbBold";
			this.cbBold.Label = global::Mono.Unix.Catalog.GetString ("Bold");
			this.cbBold.DrawIndicator = true;
			this.cbBold.UseUnderline = true;
			this.table1.Add (this.cbBold);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbBold]));
			w9.LeftAttach = ((uint)(3));
			w9.RightAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbItalic = new global::Gtk.CheckButton ();
			this.cbItalic.CanFocus = true;
			this.cbItalic.Name = "cbItalic";
			this.cbItalic.Label = global::Mono.Unix.Catalog.GetString ("Italic");
			this.cbItalic.DrawIndicator = true;
			this.cbItalic.UseUnderline = true;
			this.table1.Add (this.cbItalic);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbItalic]));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbStrikeout = new global::Gtk.CheckButton ();
			this.cbStrikeout.CanFocus = true;
			this.cbStrikeout.Name = "cbStrikeout";
			this.cbStrikeout.Label = global::Mono.Unix.Catalog.GetString ("Strikeout");
			this.cbStrikeout.DrawIndicator = true;
			this.cbStrikeout.UseUnderline = true;
			this.table1.Add (this.cbStrikeout);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbStrikeout]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(3));
			w11.RightAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbUnderline = new global::Gtk.CheckButton ();
			this.cbUnderline.CanFocus = true;
			this.cbUnderline.Name = "cbUnderline";
			this.cbUnderline.Label = global::Mono.Unix.Catalog.GetString ("Underline");
			this.cbUnderline.DrawIndicator = true;
			this.cbUnderline.UseUnderline = true;
			this.table1.Add (this.cbUnderline);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbUnderline]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lSize = new global::Gtk.Label ();
			this.lSize.Name = "lSize";
			this.lSize.Xalign = 0F;
			this.lSize.LabelProp = global::Mono.Unix.Catalog.GetString ("Size");
			this.table1.Add (this.lSize);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.lSize]));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lStretch = new global::Gtk.Label ();
			this.lStretch.Name = "lStretch";
			this.lStretch.Xalign = 0F;
			this.lStretch.LabelProp = global::Mono.Unix.Catalog.GetString ("Stretch");
			this.table1.Add (this.lStretch);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.lStretch]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.sbSize = new global::Gtk.SpinButton (4, 72, 1);
			this.sbSize.WidthRequest = 80;
			this.sbSize.CanFocus = true;
			this.sbSize.Name = "sbSize";
			this.sbSize.Adjustment.PageIncrement = 10;
			this.sbSize.ClimbRate = 1;
			this.sbSize.Numeric = true;
			this.sbSize.Value = 12;
			this.table1.Add (this.sbSize);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.sbSize]));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.sbStretch = new global::Gtk.SpinButton (0, 72, 1);
			this.sbStretch.WidthRequest = 80;
			this.sbStretch.CanFocus = true;
			this.sbStretch.Name = "sbStretch";
			this.sbStretch.Adjustment.PageIncrement = 10;
			this.sbStretch.ClimbRate = 1;
			this.sbStretch.Numeric = true;
			this.table1.Add (this.sbStretch);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.sbStretch]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(6));
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w18.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 500;
			this.DefaultHeight = 500;
			this.HasDefault = true;
			this.Show ();
		}
	}
}
