
// This file has been generated by the GUI designer. Do not modify.
namespace FontTool
{
	public partial class FontBuildWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Notebook notebook1;
		private global::Gtk.FileChooserWidget fileSaveWidget;
		private global::Gtk.Label label2;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.DrawingArea drawingarea3;
		private global::Gtk.Label label3;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Entry eWidth;
		private global::Gtk.Label lX;
		private global::Gtk.Entry eHeight;
		private global::Gtk.Button btnSave;
		private global::Gtk.Button btnCancel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FontTool.FontBuildWindow
			this.WidthRequest = 600;
			this.HeightRequest = 400;
			this.Name = "FontTool.FontBuildWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Save");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			// Container child FontTool.FontBuildWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.fileSaveWidget = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(1)));
			this.fileSaveWidget.Name = "fileSaveWidget";
			this.notebook1.Add (this.fileSaveWidget);
			global::Gtk.Notebook.NotebookChild w1 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.fileSaveWidget]));
			w1.MenuLabel = "";
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 80;
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Save");
			this.notebook1.SetTabLabel (this.fileSaveWidget, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport ();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.drawingarea3 = new global::Gtk.DrawingArea ();
			this.drawingarea3.Name = "drawingarea3";
			w2.Add (this.drawingarea3);
			this.scrolledwindow1.Add (w2);
			this.notebook1.Add (this.scrolledwindow1);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.scrolledwindow1]));
			w5.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 80;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Preview");
			this.notebook1.SetTabLabel (this.scrolledwindow1, this.label3);
			this.label3.ShowAll ();
			this.vbox2.Add (this.notebook1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
			w6.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eWidth = new global::Gtk.Entry ();
			this.eWidth.WidthRequest = 60;
			this.eWidth.CanFocus = true;
			this.eWidth.Name = "eWidth";
			this.eWidth.IsEditable = false;
			this.eWidth.InvisibleChar = '●';
			this.hbox3.Add (this.eWidth);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.eWidth]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lX = new global::Gtk.Label ();
			this.lX.Name = "lX";
			this.lX.LabelProp = global::Mono.Unix.Catalog.GetString ("X");
			this.hbox3.Add (this.lX);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lX]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eHeight = new global::Gtk.Entry ();
			this.eHeight.WidthRequest = 60;
			this.eHeight.CanFocus = true;
			this.eHeight.Name = "eHeight";
			this.eHeight.IsEditable = true;
			this.eHeight.InvisibleChar = '●';
			this.hbox3.Add (this.eHeight);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.eHeight]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnSave = new global::Gtk.Button ();
			this.btnSave.WidthRequest = 80;
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.hbox3.Add (this.btnSave);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnSave]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.WidthRequest = 80;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbox3.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnCancel]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 400;
			this.Show ();
		}
	}
}
