
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action QuitAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.EventBox eventboxNonClient;
	private global::Gtk.EventBox eventboxClient;
	private global::Gtk.VBox vboxClient;
	private global::GuiWidgets.TitleBox titlebox2;
	private global::Gtk.MenuBar menubar4;
	private global::Gtk.Alignment alignment1;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button button1;
	private global::Gtk.Entry entry1;
	private global::Gtk.ComboBoxEntry comboboxentry1;
	private global::Gtk.CheckButton checkbutton1;
	private global::Gtk.RadioButton radiobutton1;
	private global::Gtk.RadioButton radiobutton2;
	private global::Gtk.ProgressBar progressbar1;
	private global::Gtk.HScale hscale1;
	private global::Gtk.SpinButton spinbutton1;
	private global::Gtk.Calendar calendar3;
	private global::Gtk.ToggleButton togglebutton2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview3;
	private global::Gtk.Label label1;
	private global::Gtk.Statusbar statusbar2;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Decorated = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.eventboxNonClient = new global::Gtk.EventBox ();
		this.eventboxNonClient.Name = "eventboxNonClient";
		// Container child eventboxNonClient.Gtk.Container+ContainerChild
		this.eventboxClient = new global::Gtk.EventBox ();
		this.eventboxClient.Name = "eventboxClient";
		this.eventboxClient.BorderWidth = ((uint)(4));
		// Container child eventboxClient.Gtk.Container+ContainerChild
		this.vboxClient = new global::Gtk.VBox ();
		this.vboxClient.Name = "vboxClient";
		// Container child vboxClient.Gtk.Box+BoxChild
		this.titlebox2 = new global::GuiWidgets.TitleBox ();
		this.titlebox2.Events = ((global::Gdk.EventMask)(256));
		this.titlebox2.Name = "titlebox2";
		this.titlebox2.Title = "Young, strong and crazy!";
		this.titlebox2.QuitOnClose = true;
		this.titlebox2.MinimizeVisible = true;
		this.titlebox2.MaximizeVisible = true;
		this.vboxClient.Add (this.titlebox2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxClient [this.titlebox2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vboxClient.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar4\'><menu name=\'FileAction\' action=\'FileAction\'><menuite" +
			"m name=\'QuitAction\' action=\'QuitAction\'/></menu><menu name=\'HelpAction\' action=\'" +
			"HelpAction\'><menuitem name=\'AboutAction\' action=\'AboutAction\'/></menu><menu/></m" +
			"enubar></ui>");
		this.menubar4 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar4")));
		this.menubar4.Name = "menubar4";
		this.vboxClient.Add (this.menubar4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxClient [this.menubar4]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vboxClient.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w4.X = 8;
		w4.Y = 9;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.Text = global::Mono.Unix.Catalog.GetString ("Young, strong and crazy!");
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w5.X = 8;
		w5.Y = 38;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText ();
		this.comboboxentry1.AppendText (global::Mono.Unix.Catalog.GetString ("Young\r"));
		this.comboboxentry1.AppendText (global::Mono.Unix.Catalog.GetString ("strong\r"));
		this.comboboxentry1.AppendText (global::Mono.Unix.Catalog.GetString ("crazy"));
		this.comboboxentry1.Name = "comboboxentry1";
		this.comboboxentry1.Active = 0;
		this.fixed1.Add (this.comboboxentry1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboboxentry1]));
		w6.X = 8;
		w6.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton1 = new global::Gtk.CheckButton ();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("checkbutton1");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.fixed1.Add (this.checkbutton1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton1]));
		w7.X = 287;
		w7.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("radiobutton1"));
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.radiobutton1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton1]));
		w8.X = 287;
		w8.Y = 41;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("radiobutton2"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.radiobutton2);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton2]));
		w9.X = 287;
		w9.Y = 66;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progressbar1 = new global::Gtk.ProgressBar ();
		this.progressbar1.WidthRequest = 250;
		this.progressbar1.Name = "progressbar1";
		this.progressbar1.Fraction = 0.5D;
		this.fixed1.Add (this.progressbar1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.progressbar1]));
		w10.X = 8;
		w10.Y = 105;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hscale1 = new global::Gtk.HScale (null);
		this.hscale1.WidthRequest = 250;
		this.hscale1.CanFocus = true;
		this.hscale1.Name = "hscale1";
		this.hscale1.Adjustment.Upper = 100D;
		this.hscale1.Adjustment.PageIncrement = 10D;
		this.hscale1.Adjustment.StepIncrement = 1D;
		this.hscale1.Adjustment.Value = 50D;
		this.hscale1.DrawValue = true;
		this.hscale1.Digits = 0;
		this.hscale1.ValuePos = ((global::Gtk.PositionType)(3));
		this.fixed1.Add (this.hscale1);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.hscale1]));
		w11.X = 287;
		w11.Y = 105;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinbutton1 = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10D;
		this.spinbutton1.ClimbRate = 1D;
		this.spinbutton1.Numeric = true;
		this.spinbutton1.Value = 50D;
		this.fixed1.Add (this.spinbutton1);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinbutton1]));
		w12.X = 422;
		w12.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendar3 = new global::Gtk.Calendar ();
		this.calendar3.CanFocus = true;
		this.calendar3.Name = "calendar3";
		this.calendar3.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendar3);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendar3]));
		w13.X = 8;
		w13.Y = 140;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.togglebutton2 = new global::Gtk.ToggleButton ();
		this.togglebutton2.CanFocus = true;
		this.togglebutton2.Name = "togglebutton2";
		this.togglebutton2.UseUnderline = true;
		this.togglebutton2.Label = global::Mono.Unix.Catalog.GetString ("GtkToggleButton");
		this.fixed1.Add (this.togglebutton2);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.togglebutton2]));
		w14.X = 79;
		w14.Y = 9;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView ();
		this.textview3.Buffer.Text = "Young, strong and crazy!";
		this.textview3.WidthRequest = 200;
		this.textview3.HeightRequest = 150;
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.GtkScrolledWindow.Add (this.textview3);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w16.X = 169;
		w16.Y = 140;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w17.X = 193;
		w17.Y = 13;
		this.alignment1.Add (this.fixed1);
		this.vboxClient.Add (this.alignment1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxClient [this.alignment1]));
		w19.Position = 2;
		// Container child vboxClient.Gtk.Box+BoxChild
		this.statusbar2 = new global::Gtk.Statusbar ();
		this.statusbar2.Name = "statusbar2";
		this.statusbar2.Spacing = 6;
		this.vboxClient.Add (this.statusbar2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxClient [this.statusbar2]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		this.eventboxClient.Add (this.vboxClient);
		this.eventboxNonClient.Add (this.eventboxClient);
		this.Add (this.eventboxNonClient);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 601;
		this.DefaultHeight = 481;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
	}
}
