
// This file has been generated by the GUI designer. Do not modify.
namespace Template
{
	public partial class AboutWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.EventBox eventboxNonClient;
		private global::Gtk.EventBox eventboxClient;
		private global::Gtk.VBox vboxClient;
		private global::GuiWidgets.TitleBox titlebox2;
		private global::Gtk.Image image481;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textview1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Template.AboutWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Template.AboutWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("AboutWindow");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Decorated = false;
			// Container child Template.AboutWindow.Gtk.Container+ContainerChild
			this.eventboxNonClient = new global::Gtk.EventBox ();
			this.eventboxNonClient.Name = "eventboxNonClient";
			// Container child eventboxNonClient.Gtk.Container+ContainerChild
			this.eventboxClient = new global::Gtk.EventBox ();
			this.eventboxClient.Name = "eventboxClient";
			// Container child eventboxClient.Gtk.Container+ContainerChild
			this.vboxClient = new global::Gtk.VBox ();
			this.vboxClient.Name = "vboxClient";
			this.vboxClient.Spacing = 5;
			// Container child vboxClient.Gtk.Box+BoxChild
			this.titlebox2 = new global::GuiWidgets.TitleBox ();
			this.titlebox2.Events = ((global::Gdk.EventMask)(256));
			this.titlebox2.Name = "titlebox2";
			this.titlebox2.Title = "About";
			this.titlebox2.QuitOnClose = false;
			this.titlebox2.MinimizeVisible = false;
			this.titlebox2.MaximizeVisible = false;
			this.vboxClient.Add (this.titlebox2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxClient [this.titlebox2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxClient.Gtk.Box+BoxChild
			this.image481 = new global::Gtk.Image ();
			this.image481.Name = "image481";
			this.image481.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "..\\..\\..\\misc\\dgle2_logo.png"));
			this.vboxClient.Add (this.image481);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxClient [this.image481]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(5));
			// Container child vboxClient.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.Buffer.Text = "DGLE2 Template GUI App\n23.09.2012\nShestakov Mikhail aka MIKE";
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.textview1.Justification = ((global::Gtk.Justification)(2));
			this.textview1.PixelsAboveLines = 5;
			this.GtkScrolledWindow.Add (this.textview1);
			this.vboxClient.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxClient [this.GtkScrolledWindow]));
			w5.Position = 2;
			this.eventboxClient.Add (this.vboxClient);
			this.eventboxNonClient.Add (this.eventboxClient);
			this.Add (this.eventboxNonClient);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 255;
			this.DefaultHeight = 194;
			this.Show ();
		}
	}
}
